#!/usr/bin/env node

const puppeteer = require('puppeteer');
const path = require('path');
const urlx = require('url');
const meow = require('meow');

const cli = meow(`
    Usage
        $ shooty <url>

    Options
        --start           Date it will start (optional)
        --stop            Date it will stop (optional)
        --every, -e       Time between every shoot (2m,3h,1d)
        --fullpage, -f    Shoot the entire page not only the viewport (default: false)
        --mobile, -m      Enforces a mobile user agent (default: true)
        --version         Displays current version
        --help            Displays help

    Examples
        $ shooty https://google.com --every 1h
        $ shooty https://google.com --every 3h --start "10 Jul 2018 22:09:00 GMT+4" --stop "11 Jul 2018 22:09:00 GMT+4"
`, {
	flags: {
		output: {
			type: 'string',
			alias: 'o',
			default: '.'
		},
		every: {
			type: 'string',
			alias: 'e',
			default: '1h'
		},
		mobile: {
			type: 'boolean',
			alias: 'm',
			default: true
		},
		fullpage: {
			type: 'boolean',
			alias: 'f',
			default: false
		}
	}
});

const error = (msg) => {
    console.error('\x1b[31m%s\x1b[0m',`\n  Error: ${msg}`);
    cli.showHelp()
}
const isValidUrl = (str) => {
pattern = new RegExp('^(https?:\/\/)');
return pattern.test(str)
}
const extractURL = (input) => {
    let url = input[0] || null;
    if(!url){
        error("you need to specify an URL");
    }
    if(!isValidUrl(url)){
        error("please introduce a valid URL");
    }
    return url;
}
const extractInterval = (time) => {
    if(!/^\d+[mhd]$/.test(flags.every)){
        error("only minutes (5m), hours (1h) and days (2d) are accepted.");
    }
    let letter = time.substr(time.length - 1);
    let number = parseInt(time.substr(0,time.length - 1));
    let multiplier = letter == 'm' && 60 || letter == 'h' && 60*60 || letter == 'd' && 60*60*24;
    return number*1000*multiplier;
}
const getSecondsToDate = (date) => {
    if(!date) return 0;
    let start = Date.parse(date);
    if(isNaN(start)){
        return error("you need to specify a valid date format that can be parsed.\n\n  Check: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse");
    }
    secondsToDate = start - (new Date().getTime());
    if(secondsToDate < 0){
        return error("you need to specify a future date");
    }
    return secondsToDate;
}
const shoot = async (url,flags) => {

    try{
      let now = (new Date()).toLocaleTimeString();
      let name = `${flags.domain}_`+now.replace(/[:]/g,'-')+".png";
      console.log("Taking screenshot at:",now);
      const browser = await puppeteer.launch({ignoreHTTPSErrors:true});
      const page = await browser.newPage();
      page.setDefaultNavigationTimeout(60000);
      if(flags.mobile){
        page.setUserAgent('Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25');
      }
      await page.goto(url);
      await page.screenshot({path: path.format({dir:flags.o,base:name}).replace("//","/"), fullPage: flags.fullpage});
      await browser.close();
      console.log("Screenshot taken with name:",name);
    }catch(e){
        console.error('\x1b[31m%s\x1b[0m',`\n  ${e}`);
    }

};
const flags = cli.flags;
const url = extractURL(cli.input);
const interval = extractInterval(flags.every);
flags.domain = urlx.parse(url).hostname;

let interval_id = null;

function record(){
    interval_id = setInterval(shoot.bind(null,url,flags),interval);
    shoot(url,flags);
}

console.log(`Screenshot of ${flags.domain} every ${flags.every}`);
let boot = getSecondsToDate(flags.start);
if(boot > 0)
    console.log(`Will start at ${flags.start}, in ${boot/1000} seconds`);

let finish = getSecondsToDate(flags.stop);
if(finish && finish-boot > 60){
    console.log(`Will stop at ${flags.stop}, in ${finish/1000} seconds`);
    setTimeout(() => {
        clearInterval(interval_id);
        console.log(`Stopped at ${flags.stop}.`);
    },finish);
}
setTimeout(record,boot); // Start time
